### ISSUE TITLE
Deregistering a user does not remove her from the list of participants

### ISSUE THREAD

**Issue by dvberkel** [devnology/website#25]
Even though the user is mailed, the user is not removed from the list of participants

**Comment by arnetim** [comment]
Dit lijkt me niet zo spannend, gaat hier fout: https://github.com/devnology/website/blob/master/app/controllers/events_controller.rb#L38. Moet denk ik nog registration.destroy() worden aangeroepen (http://apidock.com/rails/ActiveRecord/Relation/destroy).

**Comment by dvberkel** [comment]
@arnetim wat je zegt is niet helemaal waar.

De gebruiker krijgt hier een mailtje waarop zij nog moet bevestigen dat zij zich wil uitschrijven. Zodra zij op de meegestuurde bevestig deregistratie link klikt wordt `registration.destroy()` aangeroepen, zoals te zien in [`confirm_unregistration`](https://github.com/devnology/website/blob/master/app/controllers/events_controller.rb#L73) methode.

Het probleem is dus iets subtieler dan dat.

**Comment by arnetim** [comment]
@dvberkel dat is lomp, iets te snel gereageerd :)

Vandaag mail service geswitched van Mandrill naar Sendgrid (Mandrill is niet meer gratis). Vervolgens in- en uitschrijving getest en dat werkt prima. Ook lokaal een en ander getest, maar kan het probleem niet (meer) reproduceren.

**Comment by dvberkel** [comment]
Interessant, ik zal er ook nog eens goed naar kijken. Mocht ik het ook niet kunnen reproduceren, dan sluiten we het issue

**Comment by dvberkel** [comment]
Tjeerd Hans heeft hier last van
